### ISSUE TITLE
Mirror Mist Event

### ISSUE THREAD

**Issue by SirUmnei** [AstroPenguin642/Replay-the-Spire#11]
Anytime I'd get this event, and selected the 4th option, "[Wander] Transform and upgrade a random card.", instead of doing that, it would remove Dualcast from my Deck and add Bash (which sucks). Taking the 3rd option does transform a random card however. None of the options remove my Cracked Core Relic either. Have not tested with other chars.

**Comment by The-Evil-Pickle** [comment]
This mod isn't designed to be run in the beta branch, so I've not tested things with the defect yet. The other two characters are working fine with that event.

What's weird here is that Mirror Mist should only have 3 options, not 4. What were the options you saw?

**Comment by SirUmnei** [comment]
The first two said that they required either Boiling Blood or Ring of the Snake, the third said to exchange cracked core and dualcast for bash and the last one was wander around. The latest patch seems to have fixed this somehow.
