### ISSUE TITLE
New Orbs Crash?

### ISSUE THREAD

**Issue by Deathbydoom** [AstroPenguin642/Replay-the-Spire#14]
It seems like the Hellfire Orbs crash the game when combat begins,
Reflective Lens glass orbs also crash the game when their passive effect activates.

**Comment by Deathbydoom** [comment]
Glass works fine normally,
Crystal orbs function flawlessly

**Comment by Deathbydoom** [comment]
I am talking about the hellfire orb from the Iron Core you get in the Mirror Mist Event

**Comment by Deathbydoom** [comment]
yes, could that be the problem.

**Comment by The-Evil-Pickle** [comment]
Working in current version
