### ISSUE TITLE
Divine Protection breaks with Mark of the Bloom / Muzzle

### ISSUE THREAD

**Issue by apantel** [AstroPenguin642/Replay-the-Spire#17]
If Mark of the Bloom prevents the HP from being added or Muzzle (new Neow blight) prevents the max HP from being added, they are still subtracted at the end of combat. DP + Muzzle in particular means losing 8 max HP per fight.

**Comment by The-Evil-Pickle** [comment]
New update reworks Divine Protection with a new mechanic to avoid such conflicts. Thanks for the report!
