### ISSUE TITLE
Rune of Simplicity is Missing

### ISSUE THREAD

**Issue by SirUmnei** [AstroPenguin642/Replay-the-Spire#19]
I had an Endless run where I acquired pretty much every single relic in the game (I looped through the game 5 times), and Rune of Simplicity never showed up. Not only that, but I also wasn't able to spawn it via the in-game console.

**Comment by The-Evil-Pickle** [comment]
Rune of Simplicity was causing new bugs every time the game updated it, so I've temporarily removed it until things calm down a bit.
