### ISSUE TITLE
Honey Jar - Question Card interaction bug

### ISSUE THREAD

**Issue by zajef77** [AstroPenguin642/Replay-the-Spire#2]
Having Honey Jar and Question Card triggers a really weird card choice screen, in which you can only barely see the rightmost card on the bottom left corner
![capture](https://user-images.githubusercontent.com/38325965/38687951-e639e0a0-3e45-11e8-984a-b71713afac91.PNG)

**Comment by The-Evil-Pickle** [comment]
I've just made it so these two don't try to stack; this problem should be fixed now.
