### ISSUE TITLE
Garlic doesn't work correctly with artifact

### ISSUE THREAD

**Issue by apantel** [AstroPenguin642/Replay-the-Spire#22]
On enemies with artifact, garlic applies -4 strength, and they never regain strength.

**Comment by The-Evil-Pickle** [comment]
Thanks for letting me know! I've just updated the mod with a solution to this.

**Comment by SilentJ28** [comment]
@The-Evil-Pickle New garlic applies Languid and ignores artifact.
It applied 3 languid to the sentries. They still have their artifact charge
