### ISSUE TITLE
Can't purchase cards after boss; crashes.

### ISSUE THREAD

**Issue by zardes** [AstroPenguin642/Replay-the-Spire#28]
I cannot purchase cards at the 1st shop after fighting the 2nd boss, which happened to be the Pirate with the Fish, or else it crashes. I can purchase relics, potions, and remove cards, but no buying of ANY cards. I am currently using 4 mods:
Base Mod
BetterRewards
Replay the Spire
SuperFastMode

EDIT: I also got Chewing Gum at the boss.

UPDATE: I reached the 2nd shop and can now purchase cards fine.

**Comment by The-Evil-Pickle** [comment]
I've been unable to replicate this bug, so I'm going to assume it was some conflict with other mods or old versions of the game. If something like this happens again, let us know.
