### ISSUE TITLE
Replay the spire dies while adding curses with newest basemod and Week 20 patch

### ISSUE THREAD

**Issue by notque** [AstroPenguin642/Replay-the-Spire#3]
10:02:50.371 INFO ReplayTheSpireMod.ReplayTheSpireMod> adding colorless cards...
10:02:50.397 INFO helpers.FileSaver> Save Succeeded: preferences\STSSeenCards
10:02:50.405 INFO helpers.FileSaver> Save Succeeded: preferences\STSUnlocks
10:02:50.416 INFO helpers.FileSaver> Save Succeeded: preferences\STSSeenCards
10:02:50.424 INFO helpers.FileSaver> Save Succeeded: preferences\STSUnlocks
10:02:50.434 INFO helpers.FileSaver> Save Succeeded: preferences\STSSeenCards
10:02:50.441 INFO helpers.FileSaver> Save Succeeded: preferences\STSUnlocks
10:02:50.449 INFO helpers.FileSaver> Save Succeeded: preferences\STSSeenCards
10:02:50.457 INFO helpers.FileSaver> Save Succeeded: preferences\STSUnlocks
10:02:50.457 INFO ReplayTheSpireMod.ReplayTheSpireMod> adding curses...

**Comment by The-Evil-Pickle** [comment]
Fixed. Thanks for the report!
