### ISSUE TITLE
Fix advise for ArrowHead allows unlimited upgrades

### ISSUE THREAD

**Issue by gamesme** [AstroPenguin642/Replay-the-Spire#30]
Hi,
   I have an advise for Issue #18 .
  Solution: CampfireSmithEffect.java line 65

> 				AbstractDungeon.gridSelectScreen.open(AbstractDungeon.player.masterDeck.getUpgradableCards(), 1, CampfireSmithEffect.TEXT[0], true);
Change to
>			AbstractDungeon.gridSelectScreen.open(AbstractDungeon.player.masterDeck.getUpgradableCards(), 1, CampfireSmithEffect.TEXT[0], true,false,false,false);

It makes the second card selection can not be canceled.

**Comment by The-Evil-Pickle** [comment]
Just updated the mod with a fix. While this would have worked, I wanted to change the relic to use patching instead of overriding the effect class.
