### ISSUE TITLE
Arrowhead not working

### ISSUE THREAD

**Issue by jezzen** [AstroPenguin642/Replay-the-Spire#50]
The Arrowhead relic is not letting me smith twice.

Mods:
Basemod
Replay The Spire
The Construct
BetterRewards
Always Whale

It was working a patch back when I just had Replay the Spire on, so it could be a mod conflict.

Here's the debug of when trying to smith: 
[smithing debug.txt](https://github.com/AstroPenguin642/Replay-the-Spire/files/2217799/smithing.debug.txt)

edit: Thinking over it again, I do remember having the arrowhead and trying to smith at one of those randomized campfires without it working and thinking along the lines of "It's not a regular campfire, I guess it doesn't work here", though of cause it's part of the same mod. I believe this was without any character mods, not sure if I had BetterRewards or Always Whale at that point.

**Comment by Glaargh** [comment]
I've experienced the same issue, but as far as I can tell it has nothing to do with the Construct or Always Whale, since it used to work with those mods on before a recent patch.

**Comment by Daenyth** [comment]
I noticed that you also can't cancel the smith action

**Comment by jezzen** [comment]
@Daenyth ?? Really? I know that the arrowhead did that on the second smithing to prevent infinite upgrades with smith>return>smith>repeat, but I haven't noticed it missing since it stopped working. Then again, I've only had it a couple times since it stopped working.

If this is true, it could mean the reason it isn't working is because of the smithing option going straight to the second scene and not giving the opportunity to actually get 2 upgrades.

**Comment by Daenyth** [comment]
> the smithing option going straight to the second scene

That was my guess also
