### ISSUE TITLE
Baseball does not stick through reloads games

### ISSUE THREAD

**Issue by Lunaraia** [AstroPenguin642/Replay-the-Spire#53]
as the title says, the Baseball is supposed to reduce the cost of a card to 0 upon acquiring it and it does just that to begin with, but if you quit to the main menu the effect stops working, same happens if you just quit the game flat-out, the baseball won't work upon reloading

**Comment by vizthex123** [comment]
I've noticed too that the effect doesn't stay if the card gets upgraded, and it seems to favour starter cards.
