### ISSUE TITLE
Ring of Panic + 0-cost bug

### ISSUE THREAD

**Issue by Hardrocknerd** [AstroPenguin642/Replay-the-Spire#75]
In my current run I picked up the Ring of Panic from the "Cursed Rings"-Event with the Silent. I have Neutralize and Deflect + some other cards in my deck. With every other card the Confusion works as intended, but those two cards, the only 0-costs in my deck still cost 0 energy on play although they show different numbers in my hand.

**Comment by Hardrocknerd** [comment]
Seed is 2DNKVNU7T4GHH

**Comment by The-Evil-Pickle** [comment]
This is actually an issue with the base game's code. I sent megacrit a fix for it a couple of days ago, but it probably won't be implemented until the next weekly update.
